name: pcoroneos.com ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm ci
      - run: pnpm run lint:fix
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          build: pnpm build
          start: pnpm start
